# Generated by Django 4.1.5 on 2023-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_homeslider"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslider",
            name="Image",
            field=models.FileField(upload_to="files"),
        ),
    ]
