# Generated by Django 4.1.5 on 2023-03-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_alter_homeslider_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslider",
            name="Description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
