# Generated by Django 4.1.5 on 2023-03-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0005_donate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Donate",
            new_name="Campaign",
        ),
    ]
