# Generated by Django 4.1.5 on 2023-03-30 16:40

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0006_rename_donate_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="PhoneNumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None
            ),
        ),
    ]
