# Generated by Django 4.1.5 on 2023-04-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_contact_phonenumber"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="MinimumAmount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
