# Generated by Django 4.1.5 on 2023-04-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0009_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="Email",
            field=models.EmailField(default="gauba", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="Name",
            field=models.CharField(default="gauba", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default="False"),
        ),
    ]
