# Generated by Django 4.1.5 on 2023-04-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0010_order_email_order_name_order_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="timestamp",
            field=models.CharField(default="time", max_length=100),
            preserve_default=False,
        ),
    ]
